# Generated by Django 3.0.7 on 2020-10-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0002_blog_propic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='propic',
            new_name='postpic',
        ),
    ]
